
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/flask-app-cloud-run-371417/simple_flask_app_gcp:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/flask-app-cloud-run-371417/simple_flask_app_gcp:$SHORT_SHA']
